version: "3.3"

services:
  lastfm:
    build:
      context: .
    container_name: lastfm-bot
    restart: always
    volumes:
      - /home/webuser/http/www/music:/app/music
    env_file:
      - .env
    command: ["python", "main.py"]
