version: "3.3"

services:
  mylastfmapi:
    build: .
    image: mylastfmapi:latest
    container_name: mylastfmapibot
    restart: always
    volumes:
      - /home/webuser/http/www/music:/app/music
    env_file:
      - .env
    command: ["python", "main.py"]
